"""ForestVol MVP — 3D Mesh processing and Poisson reconstruction.

Loads a .PLY point cloud generated by NodeODM, processes it using Open3D
to create a watertight mesh, scales it using the calibrated spatial scale,
and exports it as a .glb file using trimesh.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from pathlib import Path

import open3d as o3d
import trimesh
import numpy as np

logger = logging.getLogger(__name__)

# NodeODM outputs the dense point cloud here inside the download zip
ODM_FILTERED_CLOUD_NAME = "odm_filterpoints/point_cloud.ply"


@dataclass
class MeshResult:
    """Result of the 3D meshing process."""

    success: bool
    glb_path: str | None
    is_watertight: bool
    vertex_count: int
    face_count: int
    error: str | None = None


def _remove_outliers(pcd: o3d.geometry.PointCloud) -> o3d.geometry.PointCloud:
    """Apply statistical outlier removal to clean the point cloud."""
    # nb_neighbors: how many neighbors to consider for avg distance
    # std_ratio: lower means more aggressive filtering
    cl, ind = pcd.remove_statistical_outlier(nb_neighbors=20, std_ratio=2.0)
    return pcd.select_by_index(ind)


def _reconstruct_poisson(pcd: o3d.geometry.PointCloud, depth: int = 9) -> o3d.geometry.TriangleMesh:
    """Run Poisson Surface Reconstruction.

    Returns the generated mesh and the densities for filtering.
    """
    if not pcd.has_normals():
        # Estimate normals if missing (NodeODM usually provides them, but just in case)
        pcd.estimate_normals(
            search_param=o3d.geometry.KDTreeSearchParamHybrid(radius=0.1, max_nn=30)
        )
        pcd.orient_normals_consistent_tangent_plane(100)

    with o3d.utility.VerbosityContextManager(
        o3d.utility.VerbosityLevel.Warning
    ):
        mesh, densities = o3d.geometry.TriangleMesh.create_from_point_cloud_poisson(
            pcd, depth=depth
        )

    # Filter out low density triangles (extrapolations created by Poisson)
    # Threshold: remove triangles with density < 10th percentile
    densities = np.asarray(densities)
    density_threshold = np.percentile(densities, 5)
    
    vertices_to_remove = densities < density_threshold
    mesh.remove_vertices_by_mask(vertices_to_remove)
    
    return mesh


def process_point_cloud(
    session_id: str,
    processed_dir: Path,
    scale_px_per_cm: float
) -> MeshResult:
    """Process a NodeODM point cloud into a scaled, watertight GLB mesh."""
    cloud_path = processed_dir / ODM_FILTERED_CLOUD_NAME
    
    # Fallback to the generic point_cloud.ply if the filtered one doesn't exist
    if not cloud_path.exists():
        cloud_path = processed_dir / "point_cloud.ply"
        
    if not cloud_path.exists():
        logger.error("No point cloud found at %s", processed_dir)
        return MeshResult(False, None, False, 0, 0, "POINT_CLOUD_NOT_FOUND")

    try:
        # 1. Load point cloud with Open3D
        pcd = o3d.io.read_point_cloud(str(cloud_path))
        if pcd.is_empty():
            return MeshResult(False, None, False, 0, 0, "EMPTY_POINT_CLOUD")

        # 2. Filter noise
        pcd = _remove_outliers(pcd)

        # 3. Poisson Surface Reconstruction
        o3d_mesh = _reconstruct_poisson(pcd, depth=9)
        
        # Open3D's color handling is normalized [0, 1]. Trimesh uses [0, 255]
        # We'll save the intermediate mesh to a temporary file, then load with trimesh
        # because converting directly in memory can lose color data depending on versions.
        temp_ply = processed_dir / "temp_mesh.ply"
        o3d.io.write_triangle_mesh(str(temp_ply), o3d_mesh)

        # 4. Load with trimesh for repair and scaling
        mesh = trimesh.load(str(temp_ply), force='mesh')
        
        # 5. Apply spatial scaling (Convert from arbitrary/px units to meters)
        # scale_px_per_cm means 1 cm = X px.
        # We want our mesh in METERS.
        # 1 cm = 0.01 meters.
        # scale_factor = (1.0 / scale_px_per_cm) / 100.0  <- to get meters
        if scale_px_per_cm > 0:
            scale_to_meters = (1.0 / scale_px_per_cm) * 0.01
            mesh.apply_scale(scale_to_meters)

        # 6. Repair holes to make it watertight
        trimesh.repair.fill_holes(mesh)
        is_watertight = mesh.is_watertight

        # 7. Export to GLB
        glb_path = processed_dir / "model.glb"
        mesh.export(str(glb_path), file_type="glb")

        # Cleanup temp file
        if temp_ply.exists():
            temp_ply.unlink()

        return MeshResult(
            success=True,
            glb_path=str(glb_path),
            is_watertight=bool(is_watertight),
            vertex_count=len(mesh.vertices),
            face_count=len(mesh.faces),
        )

    except Exception as exc:
        logger.exception("Failed to process 3D mesh: %s", exc)
        return MeshResult(False, None, False, 0, 0, "PROCESSING_ERROR")
